#!/usr/bin/env bash
# Idempotently generate .env for the AI pipeline POC.
# Adds missing keys with random values; preserves any existing values.
# Safe to re-run anytime.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
ENV_EXAMPLE="$ROOT_DIR/.env.example"

# ---------- helpers ----------
gen_b64() { openssl rand -base64 "$1" | tr -d '\n=' | tr '/+' '_-'; }
gen_hex() { openssl rand -hex "$1"; }

# If a key is absent in $ENV_FILE, append "KEY=VALUE".
# If present, leave as-is.
ensure_key() {
  local key="$1"
  local value="$2"
  if [[ -f "$ENV_FILE" ]] && grep -qE "^${key}=" "$ENV_FILE"; then
    return 0
  fi
  printf '%s=%s\n' "$key" "$value" >>"$ENV_FILE"
  echo "  + added $key"
}

# Placeholder for user-supplied secret (added only if missing, with empty value).
ensure_placeholder() {
  local key="$1"
  if [[ -f "$ENV_FILE" ]] && grep -qE "^${key}=" "$ENV_FILE"; then
    return 0
  fi
  printf '%s=\n' "$key" >>"$ENV_FILE"
  echo "  + added $key (empty, please fill manually)"
}

# ---------- ensure env file exists ----------
if [[ ! -f "$ENV_FILE" ]]; then
  echo "Creating new .env ..."
  cat >"$ENV_FILE" <<'HEADER'
# AI Pipeline POC — Environment Variables
# Generated by scripts/bootstrap.sh. Safe to re-run; existing keys are preserved.
# DO NOT commit this file. It is gitignored.

HEADER
else
  echo "Existing .env detected. Adding missing keys only..."
fi

# ---------- shared infra secrets ----------
ensure_key POSTGRES_USER        "postgres"
ensure_key POSTGRES_PASSWORD    "$(gen_b64 24)"
ensure_key REDIS_PASSWORD       "$(gen_b64 24)"
ensure_key CLICKHOUSE_USER      "clickhouse"
ensure_key CLICKHOUSE_PASSWORD  "$(gen_b64 24)"
ensure_key MINIO_ROOT_USER      "minio"
ensure_key MINIO_ROOT_PASSWORD  "$(gen_b64 24)"

# ---------- n8n ----------
ensure_key N8N_BASIC_AUTH_USER     "admin"
ensure_key N8N_BASIC_AUTH_PASSWORD "$(gen_b64 16)"
ensure_key N8N_ENCRYPTION_KEY      "$(gen_b64 32)"

# ---------- langfuse ----------
ensure_key LANGFUSE_SALT            "$(gen_b64 16)"
ensure_key LANGFUSE_ENCRYPTION_KEY  "$(gen_hex 32)"
ensure_key NEXTAUTH_SECRET          "$(gen_b64 32)"
ensure_placeholder LANGFUSE_PUBLIC_KEY  # filled after first login (Phase 4)
ensure_placeholder LANGFUSE_SECRET_KEY

# ---------- litellm ----------
ensure_key LITELLM_MASTER_KEY "sk-$(gen_hex 24)"

# ---------- LLM provider keys (user must fill) ----------
ensure_placeholder DEEPSEEK_API_KEY
ensure_placeholder MINIMAX_API_KEY
ensure_placeholder MINIMAX_GROUP_ID

# ---------- file mode ----------
chmod 600 "$ENV_FILE"

# ---------- write .env.example (committable template) ----------
awk -F= '
  /^[[:space:]]*$/ { print; next }
  /^#/ { print; next }
  {
    k=$1
    # Keep placeholder keys as empty, redact random secrets
    if (k=="DEEPSEEK_API_KEY" || k=="MINIMAX_API_KEY" || k=="MINIMAX_GROUP_ID" || \
        k=="LANGFUSE_PUBLIC_KEY" || k=="LANGFUSE_SECRET_KEY" || \
        k=="POSTGRES_USER" || k=="CLICKHOUSE_USER" || k=="MINIO_ROOT_USER" || \
        k=="N8N_BASIC_AUTH_USER") {
      print $0
    } else {
      print k"=REPLACE_ME"
    }
  }
' "$ENV_FILE" >"$ENV_EXAMPLE"

echo
echo "Done."
echo "  .env         (chmod 600, gitignored)"
echo "  .env.example (template, committed)"
echo
echo "Next: review .env and fill DEEPSEEK_API_KEY / MINIMAX_API_KEY if you want LLM calls to work."
